// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.6.1
// source: OrderManagementSystem/addToCart/addToCart.proto

package addtocart

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Product struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Qty  int32  `protobuf:"varint,2,opt,name=qty,proto3" json:"qty,omitempty"`
}

func (x *Product) Reset() {
	*x = Product{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OrderManagementSystem_addToCart_addToCart_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_OrderManagementSystem_addToCart_addToCart_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_OrderManagementSystem_addToCart_addToCart_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetQty() int32 {
	if x != nil {
		return x.Qty
	}
	return 0
}

type AddToCartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pr     *Product `protobuf:"bytes,1,opt,name=pr,proto3" json:"pr,omitempty"`
	UserNo int32    `protobuf:"varint,2,opt,name=userNo,proto3" json:"userNo,omitempty"`
}

func (x *AddToCartRequest) Reset() {
	*x = AddToCartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OrderManagementSystem_addToCart_addToCart_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddToCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToCartRequest) ProtoMessage() {}

func (x *AddToCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_OrderManagementSystem_addToCart_addToCart_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToCartRequest.ProtoReflect.Descriptor instead.
func (*AddToCartRequest) Descriptor() ([]byte, []int) {
	return file_OrderManagementSystem_addToCart_addToCart_proto_rawDescGZIP(), []int{1}
}

func (x *AddToCartRequest) GetPr() *Product {
	if x != nil {
		return x.Pr
	}
	return nil
}

func (x *AddToCartRequest) GetUserNo() int32 {
	if x != nil {
		return x.UserNo
	}
	return 0
}

type AddToCartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success    bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrMessage string `protobuf:"bytes,2,opt,name=errMessage,proto3" json:"errMessage,omitempty"`
}

func (x *AddToCartResponse) Reset() {
	*x = AddToCartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OrderManagementSystem_addToCart_addToCart_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddToCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToCartResponse) ProtoMessage() {}

func (x *AddToCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_OrderManagementSystem_addToCart_addToCart_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToCartResponse.ProtoReflect.Descriptor instead.
func (*AddToCartResponse) Descriptor() ([]byte, []int) {
	return file_OrderManagementSystem_addToCart_addToCart_proto_rawDescGZIP(), []int{2}
}

func (x *AddToCartResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddToCartResponse) GetErrMessage() string {
	if x != nil {
		return x.ErrMessage
	}
	return ""
}

type GetProductFromUserCartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserNo int32 `protobuf:"varint,1,opt,name=userNo,proto3" json:"userNo,omitempty"`
}

func (x *GetProductFromUserCartRequest) Reset() {
	*x = GetProductFromUserCartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OrderManagementSystem_addToCart_addToCart_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProductFromUserCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductFromUserCartRequest) ProtoMessage() {}

func (x *GetProductFromUserCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_OrderManagementSystem_addToCart_addToCart_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductFromUserCartRequest.ProtoReflect.Descriptor instead.
func (*GetProductFromUserCartRequest) Descriptor() ([]byte, []int) {
	return file_OrderManagementSystem_addToCart_addToCart_proto_rawDescGZIP(), []int{3}
}

func (x *GetProductFromUserCartRequest) GetUserNo() int32 {
	if x != nil {
		return x.UserNo
	}
	return 0
}

type GetProductFromUserCartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Qty  int32  `protobuf:"varint,2,opt,name=qty,proto3" json:"qty,omitempty"`
}

func (x *GetProductFromUserCartResponse) Reset() {
	*x = GetProductFromUserCartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OrderManagementSystem_addToCart_addToCart_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProductFromUserCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductFromUserCartResponse) ProtoMessage() {}

func (x *GetProductFromUserCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_OrderManagementSystem_addToCart_addToCart_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductFromUserCartResponse.ProtoReflect.Descriptor instead.
func (*GetProductFromUserCartResponse) Descriptor() ([]byte, []int) {
	return file_OrderManagementSystem_addToCart_addToCart_proto_rawDescGZIP(), []int{4}
}

func (x *GetProductFromUserCartResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetProductFromUserCartResponse) GetQty() int32 {
	if x != nil {
		return x.Qty
	}
	return 0
}

var File_OrderManagementSystem_addToCart_addToCart_proto protoreflect.FileDescriptor

var file_OrderManagementSystem_addToCart_addToCart_proto_rawDesc = []byte{
	0x0a, 0x2f, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2f, 0x61, 0x64, 0x64, 0x54, 0x6f, 0x43, 0x61, 0x72,
	0x74, 0x2f, 0x61, 0x64, 0x64, 0x54, 0x6f, 0x43, 0x61, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x61, 0x64, 0x64, 0x74, 0x6f, 0x63, 0x61, 0x72, 0x74, 0x22, 0x2f, 0x0a, 0x07,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x71,
	0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x71, 0x74, 0x79, 0x22, 0x4e, 0x0a,
	0x10, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x22, 0x0a, 0x02, 0x70, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x61, 0x64, 0x64, 0x74, 0x6f, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x52, 0x02, 0x70, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x6f, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x6f, 0x22, 0x4d, 0x0a,
	0x11, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x1e, 0x0a, 0x0a,
	0x65, 0x72, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x65, 0x72, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x37, 0x0a, 0x1d,
	0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x55, 0x73,
	0x65, 0x72, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x4e, 0x6f, 0x22, 0x46, 0x0a, 0x1e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x43, 0x61, 0x72, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x71,
	0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x71, 0x74, 0x79, 0x32, 0xcd, 0x01,
	0x0a, 0x10, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x43, 0x61, 0x72, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x48, 0x0a, 0x09, 0x61, 0x64, 0x64, 0x54, 0x6f, 0x43, 0x61, 0x72, 0x74, 0x12,
	0x1b, 0x2e, 0x61, 0x64, 0x64, 0x74, 0x6f, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x54,
	0x6f, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x61,
	0x64, 0x64, 0x74, 0x6f, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x43, 0x61,
	0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x6f, 0x0a, 0x16,
	0x67, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x55, 0x73,
	0x65, 0x72, 0x43, 0x61, 0x72, 0x74, 0x12, 0x28, 0x2e, 0x61, 0x64, 0x64, 0x74, 0x6f, 0x63, 0x61,
	0x72, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x46, 0x72, 0x6f,
	0x6d, 0x55, 0x73, 0x65, 0x72, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x29, 0x2e, 0x61, 0x64, 0x64, 0x74, 0x6f, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x47, 0x65, 0x74,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x43,
	0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0b, 0x5a,
	0x09, 0x61, 0x64, 0x64, 0x74, 0x6f, 0x63, 0x61, 0x72, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_OrderManagementSystem_addToCart_addToCart_proto_rawDescOnce sync.Once
	file_OrderManagementSystem_addToCart_addToCart_proto_rawDescData = file_OrderManagementSystem_addToCart_addToCart_proto_rawDesc
)

func file_OrderManagementSystem_addToCart_addToCart_proto_rawDescGZIP() []byte {
	file_OrderManagementSystem_addToCart_addToCart_proto_rawDescOnce.Do(func() {
		file_OrderManagementSystem_addToCart_addToCart_proto_rawDescData = protoimpl.X.CompressGZIP(file_OrderManagementSystem_addToCart_addToCart_proto_rawDescData)
	})
	return file_OrderManagementSystem_addToCart_addToCart_proto_rawDescData
}

var file_OrderManagementSystem_addToCart_addToCart_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_OrderManagementSystem_addToCart_addToCart_proto_goTypes = []interface{}{
	(*Product)(nil),                        // 0: addtocart.Product
	(*AddToCartRequest)(nil),               // 1: addtocart.AddToCartRequest
	(*AddToCartResponse)(nil),              // 2: addtocart.AddToCartResponse
	(*GetProductFromUserCartRequest)(nil),  // 3: addtocart.GetProductFromUserCartRequest
	(*GetProductFromUserCartResponse)(nil), // 4: addtocart.GetProductFromUserCartResponse
}
var file_OrderManagementSystem_addToCart_addToCart_proto_depIdxs = []int32{
	0, // 0: addtocart.AddToCartRequest.pr:type_name -> addtocart.Product
	1, // 1: addtocart.AddToCartService.addToCart:input_type -> addtocart.AddToCartRequest
	3, // 2: addtocart.AddToCartService.getProductFromUserCart:input_type -> addtocart.GetProductFromUserCartRequest
	2, // 3: addtocart.AddToCartService.addToCart:output_type -> addtocart.AddToCartResponse
	4, // 4: addtocart.AddToCartService.getProductFromUserCart:output_type -> addtocart.GetProductFromUserCartResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_OrderManagementSystem_addToCart_addToCart_proto_init() }
func file_OrderManagementSystem_addToCart_addToCart_proto_init() {
	if File_OrderManagementSystem_addToCart_addToCart_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_OrderManagementSystem_addToCart_addToCart_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Product); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OrderManagementSystem_addToCart_addToCart_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddToCartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OrderManagementSystem_addToCart_addToCart_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddToCartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OrderManagementSystem_addToCart_addToCart_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProductFromUserCartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OrderManagementSystem_addToCart_addToCart_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProductFromUserCartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_OrderManagementSystem_addToCart_addToCart_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_OrderManagementSystem_addToCart_addToCart_proto_goTypes,
		DependencyIndexes: file_OrderManagementSystem_addToCart_addToCart_proto_depIdxs,
		MessageInfos:      file_OrderManagementSystem_addToCart_addToCart_proto_msgTypes,
	}.Build()
	File_OrderManagementSystem_addToCart_addToCart_proto = out.File
	file_OrderManagementSystem_addToCart_addToCart_proto_rawDesc = nil
	file_OrderManagementSystem_addToCart_addToCart_proto_goTypes = nil
	file_OrderManagementSystem_addToCart_addToCart_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AddToCartServiceClient is the client API for AddToCartService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AddToCartServiceClient interface {
	AddToCart(ctx context.Context, in *AddToCartRequest, opts ...grpc.CallOption) (*AddToCartResponse, error)
	GetProductFromUserCart(ctx context.Context, in *GetProductFromUserCartRequest, opts ...grpc.CallOption) (*GetProductFromUserCartResponse, error)
}

type addToCartServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAddToCartServiceClient(cc grpc.ClientConnInterface) AddToCartServiceClient {
	return &addToCartServiceClient{cc}
}

func (c *addToCartServiceClient) AddToCart(ctx context.Context, in *AddToCartRequest, opts ...grpc.CallOption) (*AddToCartResponse, error) {
	out := new(AddToCartResponse)
	err := c.cc.Invoke(ctx, "/addtocart.AddToCartService/addToCart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addToCartServiceClient) GetProductFromUserCart(ctx context.Context, in *GetProductFromUserCartRequest, opts ...grpc.CallOption) (*GetProductFromUserCartResponse, error) {
	out := new(GetProductFromUserCartResponse)
	err := c.cc.Invoke(ctx, "/addtocart.AddToCartService/getProductFromUserCart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddToCartServiceServer is the server API for AddToCartService service.
type AddToCartServiceServer interface {
	AddToCart(context.Context, *AddToCartRequest) (*AddToCartResponse, error)
	GetProductFromUserCart(context.Context, *GetProductFromUserCartRequest) (*GetProductFromUserCartResponse, error)
}

// UnimplementedAddToCartServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAddToCartServiceServer struct {
}

func (*UnimplementedAddToCartServiceServer) AddToCart(context.Context, *AddToCartRequest) (*AddToCartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddToCart not implemented")
}
func (*UnimplementedAddToCartServiceServer) GetProductFromUserCart(context.Context, *GetProductFromUserCartRequest) (*GetProductFromUserCartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductFromUserCart not implemented")
}

func RegisterAddToCartServiceServer(s *grpc.Server, srv AddToCartServiceServer) {
	s.RegisterService(&_AddToCartService_serviceDesc, srv)
}

func _AddToCartService_AddToCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddToCartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddToCartServiceServer).AddToCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/addtocart.AddToCartService/AddToCart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddToCartServiceServer).AddToCart(ctx, req.(*AddToCartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddToCartService_GetProductFromUserCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductFromUserCartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddToCartServiceServer).GetProductFromUserCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/addtocart.AddToCartService/GetProductFromUserCart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddToCartServiceServer).GetProductFromUserCart(ctx, req.(*GetProductFromUserCartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AddToCartService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "addtocart.AddToCartService",
	HandlerType: (*AddToCartServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "addToCart",
			Handler:    _AddToCartService_AddToCart_Handler,
		},
		{
			MethodName: "getProductFromUserCart",
			Handler:    _AddToCartService_GetProductFromUserCart_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "OrderManagementSystem/addToCart/addToCart.proto",
}
